return {
    data = {
        animations = {
            -- IDLE (default)
            {
                animation_id = "default",
                duration = 2.0,
                animation_keys = {
                    -- BODY Scale Y (breathing)
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_value = 1.0,
                        end_value = 0.93,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_value = 0.93,
                        end_value = 1.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 1.0,
                    },
                    -- BODY Position Y (breathing bob)
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 0.0,
                        end_value = -2.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = -2.0,
                        end_value = 0.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 1.0,
                    },

                    -- HEAD Position Y
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 350.0,
                        end_value = 343.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 343.0,
                        end_value = 350.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 1.0,
                    },

                    -- WEAPON Position Y
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 150.0,
                        end_value = 146.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 146.0,
                        end_value = 150.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 1.0,
                    },
                    -- WEAPON Rotation Z (euler.z)
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = -10.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = -10.0,
                        end_value = 0.0,
                        duration = 1.0,
                        easing = "inoutquad",
                        start_time = 1.0,
                    },
                },
            },

            -- WALK (loop)
            {
                animation_id = "walk",
                duration = 0.8,
                animation_keys = {
                    -- BODY Bob Up & Down
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 0.0,
                        end_value = 6.0,
                        duration = 0.2,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 6.0,
                        end_value = 0.0,
                        duration = 0.2,
                        easing = "inquad",
                        start_time = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 0.0,
                        end_value = 6.0,
                        duration = 0.2,
                        easing = "outquad",
                        start_time = 0.4,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 6.0,
                        end_value = 0.0,
                        duration = 0.2,
                        easing = "inquad",
                        start_time = 0.6,
                    },
                    -- BODY Forward Tilt
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = -6.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = -6.0,
                        end_value = 0.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.4,
                    },

                    -- HEAD Bobbing and swaying forward/back
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 350.0,
                        end_value = 354.0,
                        duration = 0.2,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 354.0,
                        end_value = 346.0,
                        duration = 0.2,
                        easing = "inquad",
                        start_time = 0.2,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 346.0,
                        end_value = 354.0,
                        duration = 0.2,
                        easing = "outquad",
                        start_time = 0.4,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 354.0,
                        end_value = 350.0,
                        duration = 0.2,
                        easing = "inquad",
                        start_time = 0.6,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = 0.0,
                        end_value = 4.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = 4.0,
                        end_value = 0.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.4,
                    },

                    -- WEAPON swinging back and forth
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 70.0,
                        end_value = 50.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 50.0,
                        end_value = 70.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.4,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = 25.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 25.0,
                        end_value = 0.0,
                        duration = 0.4,
                        easing = "inoutquad",
                        start_time = 0.4,
                    },
                },
            },

            -- ATTACK (one-off)
            {
                animation_id = "attack",
                duration = 0.6,
                animation_keys = {
                    -- BODY Windup (moves back) -> Slash (lunges forward) -> Recover
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_value = 0.0,
                        end_value = -12.0,
                        duration = 0.15,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_value = -12.0,
                        end_value = 20.0,
                        duration = 0.15,
                        easing = "inoutcubic",
                        start_time = 0.15,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_value = 20.0,
                        end_value = 0.0,
                        duration = 0.3,
                        easing = "inoutquad",
                        start_time = 0.3,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = 8.0,
                        duration = 0.15,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = 8.0,
                        end_value = -15.0,
                        duration = 0.15,
                        easing = "inoutcubic",
                        start_time = 0.15,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = -15.0,
                        end_value = 0.0,
                        duration = 0.3,
                        easing = "inoutquad",
                        start_time = 0.3,
                    },

                    -- HEAD movement lagging slightly
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = 0.0,
                        end_value = -8.0,
                        duration = 0.15,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = -8.0,
                        end_value = 15.0,
                        duration = 0.15,
                        easing = "inoutcubic",
                        start_time = 0.15,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = 15.0,
                        end_value = 0.0,
                        duration = 0.3,
                        easing = "inoutquad",
                        start_time = 0.3,
                    },

                    -- WEAPON Draw back -> Slash -> Recover
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 70.0,
                        end_value = 45.0,
                        duration = 0.15,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 45.0,
                        end_value = 105.0,
                        duration = 0.12,
                        easing = "incubic",
                        start_time = 0.15,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 105.0,
                        end_value = 70.0,
                        duration = 0.33,
                        easing = "outquad",
                        start_time = 0.27,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 150.0,
                        end_value = 195.0,
                        duration = 0.15,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 195.0,
                        end_value = 100.0,
                        duration = 0.12,
                        easing = "incubic",
                        start_time = 0.15,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 100.0,
                        end_value = 150.0,
                        duration = 0.33,
                        easing = "outquad",
                        start_time = 0.27,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = 75.0,
                        duration = 0.15,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 75.0,
                        end_value = -85.0,
                        duration = 0.12,
                        easing = "incubic",
                        start_time = 0.15,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = -85.0,
                        end_value = 0.0,
                        duration = 0.33,
                        easing = "outquad",
                        start_time = 0.27,
                    },
                },
            },

            -- DAMAGE (one-off)
            {
                animation_id = "damage",
                duration = 0.4,
                animation_keys = {
                    -- BODY Knockback -> Recover
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_value = 0.0,
                        end_value = -22.0,
                        duration = 0.08,
                        easing = "outexpo",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_value = -22.0,
                        end_value = 0.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = 14.0,
                        duration = 0.08,
                        easing = "outexpo",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = 14.0,
                        end_value = 0.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },
                    -- BODY Squash
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_value = 1.0,
                        end_value = 0.75,
                        duration = 0.08,
                        easing = "outexpo",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_value = 0.75,
                        end_value = 1.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },

                    -- HEAD recoil
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = 0.0,
                        end_value = -32.0,
                        duration = 0.08,
                        easing = "outexpo",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = -32.0,
                        end_value = 0.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },

                    -- WEAPON recoil
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 70.0,
                        end_value = 42.0,
                        duration = 0.08,
                        easing = "outexpo",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 42.0,
                        end_value = 70.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = 35.0,
                        duration = 0.08,
                        easing = "outexpo",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 35.0,
                        end_value = 0.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },

                    -- RED FLASH on body and head sprite tint
                    {
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_g",
                        start_value = 1.0,
                        end_value = 0.1,
                        duration = 0.08,
                        easing = "linear",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_g",
                        start_value = 0.1,
                        end_value = 1.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },
                    {
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_b",
                        start_value = 1.0,
                        end_value = 0.1,
                        duration = 0.08,
                        easing = "linear",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_b",
                        start_value = 0.1,
                        end_value = 1.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },

                    {
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_g",
                        start_value = 1.0,
                        end_value = 0.1,
                        duration = 0.08,
                        easing = "linear",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_g",
                        start_value = 0.1,
                        end_value = 1.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },
                    {
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_b",
                        start_value = 1.0,
                        end_value = 0.1,
                        duration = 0.08,
                        easing = "linear",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_b",
                        start_value = 0.1,
                        end_value = 1.0,
                        duration = 0.32,
                        easing = "outquad",
                        start_time = 0.08,
                    },
                },
            },

            -- DEATH (one-off with fade out)
            {
                animation_id = "death",
                duration = 1.0,
                animation_keys = {
                    -- BODY falls down, rotates, and squashes
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_value = 0.0,
                        end_value = -30.0,
                        duration = 0.6,
                        easing = "outbounce",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = -90.0,
                        duration = 0.6,
                        easing = "outbounce",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_value = 1.0,
                        end_value = 0.2,
                        duration = 0.6,
                        easing = "outbounce",
                        start_time = 0.0,
                    },

                    -- HEAD rolls away to the left and falls
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_value = 0.0,
                        end_value = -55.0,
                        duration = 0.7,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 350.0,
                        end_value = -25.0,
                        duration = 0.6,
                        easing = "outbounce",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "head",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = -180.0,
                        duration = 0.7,
                        easing = "outquad",
                        start_time = 0.0,
                    },

                    -- WEAPON drops and slides to the right
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 70.0,
                        end_value = 115.0,
                        duration = 0.6,
                        easing = "outquad",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 150.0,
                        end_value = -32.0,
                        duration = 0.5,
                        easing = "outbounce",
                        start_time = 0.0,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_value = 0.0,
                        end_value = -85.0,
                        duration = 0.5,
                        easing = "outbounce",
                        start_time = 0.0,
                    },

                    -- FADE OUT alpha for sprites
                    {
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_a",
                        start_value = 1.0,
                        end_value = 0.0,
                        duration = 0.4,
                        easing = "linear",
                        start_time = 0.5,
                    },
                    {
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_a",
                        start_value = 1.0,
                        end_value = 0.0,
                        duration = 0.4,
                        easing = "linear",
                        start_time = 0.5,
                    },
                    {
                        key_type = "tween",
                        node_id = "melee_weapon#sprite",
                        property_id = "color_a",
                        start_value = 1.0,
                        end_value = 0.0,
                        duration = 0.4,
                        easing = "linear",
                        start_time = 0.5,
                    },
                },
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {},
            gui_path = "first_anim/first_anim.collection",
            layers = {},
            settings = {
                font_size = 30,
            },
            template_animation_paths = {},
        },
        nodes = {},
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}
