local panthera = require("panthera.panthera")
local animation = require("first_anim.first_anim_panthera")

local ANIMATIONS = { "default", "walk", "attack", "damage", "death" }

function init(self)
	self.animation = panthera.create_go(animation)
	self.current_anim_index = 1
	panthera.play(self.animation, ANIMATIONS[self.current_anim_index], {
		is_loop = true
	})

	msg.post(".", "acquire_input_focus")

	-- Reload animation when window is focused, only for debug and on desktop
	-- Need enable hot_reload animation and point the desktop path to the project folder
	window.set_listener(function(_, event)
		if event == window.WINDOW_EVENT_FOCUS_GAINED then
			panthera.reload_animation()
		end
	end)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		self.current_anim_index = self.current_anim_index + 1
		if self.current_anim_index > #ANIMATIONS then
			self.current_anim_index = 1
		end
		local anim_name = ANIMATIONS[self.current_anim_index]
		print("Playing animation: " .. anim_name)
		
		-- Loop only for idle (default) and walk
		local loop = (anim_name == "default" or anim_name == "walk")
		panthera.play(self.animation, anim_name, {
			is_loop = loop
		})
	end
end
