return {
    data = {
        animations = {
            {
                animation_id = "default",
                animation_keys = {
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = -10,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = -2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = 0.93,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = 146,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 80,
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = 343,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 250,
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 1,
                        start_value = -2,
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_time = 1,
                        start_value = -10,
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_time = 1,
                        start_value = 0.93,
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = 150,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_time = 1,
                        start_value = 146,
                    },
                    {
                        duration = 1,
                        easing = "inoutquad",
                        end_value = 350,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_time = 1,
                        start_value = 343,
                    },
                },
                duration = 2,
            },
            {
                animation_id = "walk",
                animation_keys = {
                    {
                        duration = 0.2,
                        easing = "outquad",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.2,
                        easing = "outquad",
                        end_value = 354,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 250,
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        end_value = -6,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        end_value = 4,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        end_value = 25,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        end_value = 50,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 90,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.2,
                        start_value = 6,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = 346,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_time = 0.2,
                        start_value = 354,
                    },
                    {
                        duration = 0.2,
                        easing = "outquad",
                        end_value = 6,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.4,
                    },
                    {
                        duration = 0.2,
                        easing = "outquad",
                        end_value = 354,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_time = 0.4,
                        start_value = 346,
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_time = 0.4,
                        start_value = -6,
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_time = 0.4,
                        start_value = 4,
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_time = 0.4,
                        start_value = 25,
                    },
                    {
                        duration = 0.4,
                        easing = "inoutquad",
                        end_value = 70,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_time = 0.4,
                        start_value = 50,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = 6,
                    },
                    {
                        duration = 0.2,
                        easing = "inquad",
                        end_value = 350,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_time = 0.6,
                        start_value = 354,
                    },
                },
                duration = 0.8,
            },
            {
                animation_id = "attack",
                animation_keys = {
                    {
                        duration = 0.15,
                        easing = "outquad",
                        end_value = -12,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.15,
                        easing = "outquad",
                        end_value = -8,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.15,
                        easing = "outquad",
                        end_value = 8,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.15,
                        easing = "outquad",
                        end_value = 45,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 90,
                    },
                    {
                        duration = 0.15,
                        easing = "outquad",
                        end_value = 75,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.15,
                        easing = "outquad",
                        end_value = 195,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 80,
                    },
                    {
                        duration = 0.12,
                        easing = "incubic",
                        end_value = -85,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_time = 0.15,
                        start_value = 75,
                    },
                    {
                        duration = 0.12,
                        easing = "incubic",
                        end_value = 100,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_time = 0.15,
                        start_value = 195,
                    },
                    {
                        duration = 0.12,
                        easing = "incubic",
                        end_value = 105,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_time = 0.15,
                        start_value = 45,
                    },
                    {
                        duration = 0.15,
                        easing = "inoutcubic",
                        end_value = -15,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_time = 0.15,
                        start_value = 8,
                    },
                    {
                        duration = 0.15,
                        easing = "inoutcubic",
                        end_value = 15,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_time = 0.15,
                        start_value = -8,
                    },
                    {
                        duration = 0.15,
                        easing = "inoutcubic",
                        end_value = 20,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_time = 0.15,
                        start_value = -12,
                    },
                    {
                        duration = 0.33,
                        easing = "outquad",
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_time = 0.27,
                        start_value = -85,
                    },
                    {
                        duration = 0.33,
                        easing = "outquad",
                        end_value = 70,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_time = 0.27,
                        start_value = 105,
                    },
                    {
                        duration = 0.33,
                        easing = "outquad",
                        end_value = 150,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_time = 0.27,
                        start_value = 100,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_time = 0.3,
                        start_value = 20,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_time = 0.3,
                        start_value = -15,
                    },
                    {
                        duration = 0.3,
                        easing = "inoutquad",
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_time = 0.3,
                        start_value = 15,
                    },
                },
                duration = 0.6,
            },
            {
                animation_id = "damage",
                animation_keys = {
                    {
                        duration = 0.08,
                        easing = "outexpo",
                        end_value = -32,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.08,
                        easing = "outexpo",
                        end_value = -22,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        end_value = 0.1,
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        end_value = 0.1,
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        end_value = 0.1,
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_b",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "linear",
                        end_value = 0.1,
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_g",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "outexpo",
                        end_value = 0.75,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_value = 1,
                    },
                    {
                        duration = 0.08,
                        easing = "outexpo",
                        end_value = 14,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.08,
                        easing = "outexpo",
                        end_value = 35,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.08,
                        easing = "outexpo",
                        end_value = 42,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 90,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_x",
                        start_time = 0.08,
                        start_value = -22,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                        start_time = 0.08,
                        start_value = 14,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                        start_time = 0.08,
                        start_value = -32,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                        start_time = 0.08,
                        start_value = 35,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_x",
                        start_time = 0.08,
                        start_value = 0.75,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_b",
                        start_time = 0.08,
                        start_value = 0.1,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_g",
                        start_time = 0.08,
                        start_value = 0.1,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_b",
                        start_time = 0.08,
                        start_value = 0.1,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_g",
                        start_time = 0.08,
                        start_value = 0.1,
                    },
                    {
                        duration = 0.32,
                        easing = "outquad",
                        end_value = 70,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_time = 0.08,
                        start_value = 42,
                    },
                },
                duration = 0.4,
            },
            {
                animation_id = "death",
                animation_keys = {
                    {
                        duration = 0.5,
                        easing = "outbounce",
                        end_value = -85,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.5,
                        easing = "outbounce",
                        end_value = -32,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_y",
                        start_value = 80,
                    },
                    {
                        duration = 0.6,
                        easing = "outbounce",
                        end_value = -90,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.6,
                        easing = "outbounce",
                        end_value = -30,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "position_y",
                    },
                    {
                        duration = 0.6,
                        easing = "outbounce",
                        end_value = -25,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_y",
                        start_value = 250,
                    },
                    {
                        duration = 0.6,
                        easing = "outbounce",
                        end_value = 0.2,
                        key_type = "tween",
                        node_id = "body",
                        property_id = "scale_y",
                        start_value = 1,
                    },
                    {
                        duration = 0.6,
                        easing = "outquad",
                        end_value = 115,
                        key_type = "tween",
                        node_id = "melee_weapon",
                        property_id = "position_x",
                        start_value = 90,
                    },
                    {
                        duration = 0.7,
                        easing = "outquad",
                        end_value = -180,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "rotation_z",
                    },
                    {
                        duration = 0.7,
                        easing = "outquad",
                        end_value = -55,
                        key_type = "tween",
                        node_id = "head",
                        property_id = "position_x",
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "body#sprite",
                        property_id = "color_a",
                        start_time = 0.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "head#sprite",
                        property_id = "color_a",
                        start_time = 0.5,
                        start_value = 1,
                    },
                    {
                        duration = 0.4,
                        easing = "linear",
                        key_type = "tween",
                        node_id = "melee_weapon#sprite",
                        property_id = "color_a",
                        start_time = 0.5,
                        start_value = 1,
                    },
                },
                duration = 1,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "first_anim/first_anim.collection",
            layers = {
            },
            settings = {
                font_size = 30,
            },
            template_animation_paths = {
            },
        },
        nodes = {
            -- ROOT
            {
                node_id = "root",
                node_index = 1,
                node_type = "box",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_x = 1,
                size_y = 1,
                visible = true,
                enabled = true,
            },
            -- BODY
            {
                node_id = "body",
                node_index = 2,
                node_type = "box",
                parent = "root",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_x = 159,
                size_y = 366,
                visible = true,
                enabled = true,
            },
            -- BODY SPRITE
            {
                node_id = "body#sprite",
                node_index = 3,
                node_type = "box",
                parent = "body",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_x = 159,
                size_y = 366,
                visible = true,
                enabled = true,
            },
            -- HEAD
            {
                node_id = "head",
                node_index = 4,
                node_type = "box",
                parent = "root",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_x = 168,
                size_y = 168,
                visible = true,
                enabled = true,
            },
            -- HEAD SPRITE
            {
                node_id = "head#sprite",
                node_index = 5,
                node_type = "box",
                parent = "head",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_x = 168,
                size_y = 168,
                visible = true,
                enabled = true,
            },
            -- WEAPON
            {
                node_id = "melee_weapon",
                node_index = 6,
                node_type = "box",
                parent = "root",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_x = 45,
                size_y = 218,
                visible = true,
                enabled = true,
            },
            -- WEAPON SPRITE
            {
                node_id = "melee_weapon#sprite",
                node_index = 7,
                node_type = "box",
                parent = "melee_weapon",
                scale_x = 1,
                scale_y = 1,
                scale_z = 1,
                size_x = 45,
                size_y = 218,
                visible = true,
                enabled = true,
            },
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}