embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"pixel\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 160.0\n"
  "  y: 20.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/example/assets/example.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "label"
  type: "label"
  data: "size {\n"
  "  x: 200.0\n"
  "  y: 30.0\n"
  "}\n"
  "outline {\n"
  "  x: 0.0\n"
  "  y: 0.0\n"
  "  z: 0.0\n"
  "  w: 1.0\n"
  "}\n"
  "shadow {\n"
  "  x: 0.0\n"
  "  y: 0.0\n"
  "  z: 0.0\n"
  "  w: 0.0\n"
  "}\n"
  "text: \"\"\n"
  "font: \"/example/assets/troika.font\"\n"
  "material: \"/builtins/fonts/label-df.material\"\n"
  "pivot: PIVOT_CENTER\n"
  ""
  position {
    y: 25.0
  }
}
