embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"ui_rect_round_16\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "size {\n"
  "  x: 64.0\n"
  "  y: 64.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/example/assets/example.atlas\"\n"
  "}\n"
  ""
}
